authentication:
    google:
        clientId:
        clientSecret:
        authUrlBase: http://localhost:${server.port}/api/authentication/fake/google/auth
        tokenUrl: http://localhost:${server.port}/api/authentication/fake/google/token
        userProfileUrl: http://localhost:${server.port}/api/authentication/fake/google/user
